name: npm test with dynamic matrix
on:
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{\"os\":\"ubuntu-latest\",\"version\":\"lts/*\"},{\"os\":\"ubuntu-latest\",\"version\":\"14\"},{\"os\":\"ubuntu-latest\",\"version\":\"12\"},{\"os\":\"ubuntu-18.04\",\"version\":\"lts/*\"},{\"os\":\"ubuntu-18.04\",\"version\":\"14\"}]}"
  run-npm-install:
    needs: set-matrix
    strategy:
      matrix: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.version }}
        - name: run install
          shell: bash
          run: |
            npm install
            npm test