name: npm test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
        - name: run install
          shell: bash
          run: |
            npm install
            npm test
  build_docker:
    if: ${{ github.ref == master }}
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t ${{ github.sha }} .
