name: npm test with matrix
on:
  workflow_dispatch:

jobs:
  run-npm-install:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        version: ["14", "lts/*"]
        include:
          - version: 12
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.version }}
        - name: run install
          shell: bash
          run: |
            npm install
            npm test